name: ThumbsApply
main: me.Todkommt.ThumbsApply.ThumbsApply
version: 2.2
website: http://www.minecraft-thumbs-up.de.tl
author: Todkommt
description: >
             Automatic Guest Promoting
commands:
  apply:
    description: Applicate yourself
permissions:
    ThumbsApply.NotGuest:
        description: Shows that you are not a guest.
        default: op